export interface FallbackProject {
  id: number;
  title: string;
  description: string;
  tags: string[];
  image: string;
  url: string;
  sortOrder: number | null;
  category?: string;
}

export const fallbackProjects: FallbackProject[] = [
  {
    id: 1,
    title: "Signature Stitch",
    description: "A premium e-commerce clothing brand store for men's wear with modern design.",
    tags: ["E-commerce", "Clothing", "Premium"],
    image: "https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=800&q=80",
    url: "https://www.signaturestitchs.com",
    sortOrder: 1,
    category: "Custom E-commerce Stores",
  },
  {
    id: 2,
    title: "My Dollar Store",
    description: "An online electronics store offering a wide range of gadgets and accessories.",
    tags: ["E-commerce", "Electronics"],
    image: "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=800&q=80",
    url: "https://mydollarstore.vercel.app/",
    sortOrder: 2,
    category: "Electronic Products",
  },
  {
    id: 3,
    title: "FlashBuy",
    description: "A fast and convenient online shopping platform for everyday services.",
    tags: ["E-commerce", "Online Services"],
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80",
    url: "https://flashbuy.vercel.app/",
    sortOrder: 3,
    category: "Custom E-commerce Stores",
  },
  {
    id: 4,
    title: "Food Express",
    description: "A fast food restaurant website with online ordering and menu showcase.",
    tags: ["Fast Food", "Restaurant", "Online Ordering"],
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80",
    url: "https://foodexpresslalkurti.vercel.app/",
    sortOrder: 4,
    category: "Fast Food",
  },
  {
    id: 5,
    title: "Skyrocket Growth Hub",
    description: "Social media management services to grow your brand presence online.",
    tags: ["Social Media", "Marketing", "Growth"],
    image: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&q=80",
    url: "https://skyrocket-growth-hub.vercel.app/",
    sortOrder: 5,
    category: "Social Media Services",
  },
  {
    id: 6,
    title: "Chohan's Style",
    description: "A modern hairstyle and barbershop business with online booking.",
    tags: ["Hairstyle", "Barbershop", "Booking"],
    image: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&q=80",
    url: "https://chohan-s-style-dsaa.vercel.app/",
    sortOrder: 6,
    category: "Hairstyle Businesses",
  },
  {
    id: 7,
    title: "TradeLink",
    description: "An innovative online startup idea connecting traders and businesses.",
    tags: ["Startup", "Trading", "B2B"],
    image: "https://images.unsplash.com/photo-1556761175-b413da4baf72?w=800&q=80",
    url: "https://tradelink-sooty.vercel.app/",
    sortOrder: 7,
    category: "Online Startup Ideas",
  },
  {
    id: 8,
    title: "FWZ PK",
    description: "A multilevel marketing platform with referral and commission tracking.",
    tags: ["MLM", "Marketing", "Referral"],
    image: "https://images.unsplash.com/photo-1556761175-4b46a572b786?w=800&q=80",
    url: "https://fwz-pk.vercel.app/",
    sortOrder: 8,
    category: "Multilevel Marketing",
  },
  {
    id: 9,
    title: "Spectra Holdings Group",
    description: "A premium real estate business showcasing properties and investment opportunities.",
    tags: ["Real Estate", "Property", "Investment"],
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80",
    url: "https://spectra-holdings-group.vercel.app/",
    sortOrder: 9,
    category: "Real Estate",
  },
  {
    id: 10,
    title: "Rayan Catering",
    description: "An event management and catering service for weddings and corporate events.",
    tags: ["Catering", "Events", "Management"],
    image: "https://images.unsplash.com/photo-1555244162-803834f70033?w=800&q=80",
    url: "https://rayancatering.vercel.app/",
    sortOrder: 10,
    category: "Event Management",
  },
  {
    id: 11,
    title: "Batch Trade",
    description: "A dynamic trade platform designed for seamless B2B trade interactions.",
    tags: ["Trade", "B2B", "Platform"],
    image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800&q=80",
    url: "https://batch-trade.vercel.app/",
    sortOrder: 11,
    category: "Trade Platform",
  },
  {
    id: 12,
    title: "Royal Dairy Life",
    description: "A fresh and engaging online presence for organic dairy products.",
    tags: ["Dairy", "Organic", "Fresh"],
    image: "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=800&q=80",
    url: "https://royaldairylife.vercel.app/",
    sortOrder: 12,
    category: "Dairy Business",
  },
  {
    id: 13,
    title: "Ice Cream Shop",
    description: "A delightful e-commerce ice cream shop with online ordering, flavor showcase, and a sweet, modern design.",
    tags: ["E-commerce", "Ice Cream", "Online Ordering"],
    image: "https://images.unsplash.com/photo-1567206563064-6f60f40a2b57?w=800&q=80",
    url: "https://ice-cream-shop-woad.vercel.app/",
    sortOrder: 13,
    category: "Custom E-commerce Stores",
  },
];

export const fallbackCategories = [
  { id: 1, name: "Fast Food", icon: "fa-utensils", sortOrder: 1, createdAt: "" },
  { id: 2, name: "Hairstyle Businesses", icon: "fa-cut", sortOrder: 2, createdAt: "" },
  { id: 3, name: "Electronic Products", icon: "fa-laptop", sortOrder: 3, createdAt: "" },
  { id: 4, name: "Custom E-commerce Stores", icon: "fa-shopping-cart", sortOrder: 4, createdAt: "" },
  { id: 5, name: "Professional Services", icon: "fa-briefcase", sortOrder: 5, createdAt: "" },
  { id: 6, name: "Health & Fitness", icon: "fa-dumbbell", sortOrder: 6, createdAt: "" },
  { id: 7, name: "Social Media Services", icon: "fa-hashtag", sortOrder: 7, createdAt: "" },
  { id: 8, name: "Online Startup Ideas", icon: "fa-lightbulb", sortOrder: 8, createdAt: "" },
  { id: 9, name: "Multilevel Marketing", icon: "fa-network-wired", sortOrder: 9, createdAt: "" },
  { id: 10, name: "Real Estate", icon: "fa-home", sortOrder: 10, createdAt: "" },
  { id: 11, name: "Event Management", icon: "fa-calendar-check", sortOrder: 11, createdAt: "" },
  { id: 12, name: "Trade Platform", icon: "fa-exchange-alt", sortOrder: 12, createdAt: "" },
  { id: 13, name: "Dairy Business", icon: "fa-cow", sortOrder: 13, createdAt: "" },
];
